AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Name: lambda-janitor
    Description: Cron job for deleting old, unused versions of Lambda functions to clean up storage space
    Author: Lumigo
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README.md
    Labels: ['lambda', 'cron']
    HomePageUrl: https://github.com/lumigo/SAR-Lambda-Janitor
    SemanticVersion: 1.7.0
    SourceCodeUrl: https://github.com/lumigo/SAR-Lambda-Janitor

Resources:
  Clean:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions/clean.handler
      Runtime: nodejs22.x
      Timeout: 900
      Environment:
        Variables:
          LOG_LEVEL: INFO
          VERSIONS_TO_KEEP:
            Ref: VersionsToKeep
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - lambda:DeleteFunction
              - lambda:List*
            Resource: "*"
      Events:
        CleanScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: !Ref CleanSchedule

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Clean}
      RetentionInDays: !Ref LogRetentionInDays

Parameters:
  CleanSchedule:
    Type: String
    Description: >-
      How frequently to run the janitor, as an EventBridge schedule expression.
      https://docs.aws.amazon.com/eventbridge/latest/userguide/scheduled-events.html
    Default: rate(1 hour)

  LogRetentionInDays:
    Type: Number
    Description: >-
      How long to retain the execution logs for the janitor.
    Default: 14
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]

  VersionsToKeep:
    Type: Number
    Description: >-
      How many versions to keep, even if they are not aliased.
    Default: 3
    MinValue: 0 # don't keep anything except $LATEST
